export { default as youtubeLogo } from "./youtube-fill.png";
export { default as sidebar } from "./side-bar-fill.png";
export {default as mic} from "./mic-line.png";
export {default as loginbar} from "./login-box-line.png";
export { default as home } from "./home-8-fill.png";
export { default as download } from "./download-line.png";
export {default as histroy} from "./histroy-line.png";
export {default as playlist} from "./play-list-line.png";
export {default as like} from "./thumb-up-line.png";
export {default as watchlater} from "./timer-2-line.png";